# Generated by Django 5.1.7 on 2025-03-14 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_action', models.CharField(blank=True, choices=[('user_message', 'Message utilisateur'), ('user_join', 'Rejoindre la salle'), ('user_leave', 'Quitter la salle')], default='user_message', max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('private', 'Message privé'), ('public', 'Message public')], default='public', max_length=255, null=True)),
                ('recipients', models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='chat_messag_room_id_e4cd0d_idx')],
            },
        ),
    ]
