# Generated by Django 5.1.7 on 2025-03-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_rename_type_message_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_action',
        ),
        migrations.AddField(
            model_name='message',
            name='action',
            field=models.CharField(blank=True, choices=[('private', 'Envoyer un message privé'), ('public', 'Envoyer un message public'), ('join', 'Rejoindre une salle'), ('leave', 'Quitter une salle')], default='private', max_length=255, null=True),
        ),
    ]
